(#108) correctly set sound volume depending on it's type
ForNeVeR/bloodmasters pull request #109
Opened 2023-08-26 16:55 UTC by KeterSCP

Fixes #108

2023-08-26 17:23 UTC, KeterSCP commented
This depends on https://github.com/ForNeVeR/bloodmasters/pull/107

2023-08-27 13:48 UTC, ForNeVeR requested changes

2023-08-27 13:48 UTC, ForNeVeR commented on Source/Client/Sound/SoundSystem.cs
> +        musicvolume = CalcVolumeScale(General.config.ReadSetting("musicvolume", 100) / 100f);
In the old code, the default music volume was 50. Let's make it so here as well?

2023-08-27 20:15 UTC, ForNeVeR approved these changes
Thanks!

2023-08-27 20:17 UTC, merged