(#34) Fixes the starting point of the bullet trajectory
ForNeVeR/bloodmasters pull request #150
Opened 2023-10-11 05:38 UTC by y0ung3r

Closes #34

2023-10-11 10:08 UTC, KeterSCP commented
This change only fixes simple bullet (fired by `WLightChaingun` and `WMinigun`) starting point.

But there are other types of bullets in the game, some of them are rendered on the server (because their movement needs to be calculated on the server) like `PlasmaBall`

2023-10-11 10:21 UTC, y0ung3r commented
@KeterSCP Thank you! I didn't know about these subtleties. I will translate the PR into a draft

2023-10-11 22:07 UTC, KeterSCP commented
Seems like this pr also changes bullet's trajectories:

Main:

https://github.com/ForNeVeR/bloodmasters/assets/38229504/2b9248d4-0ab3-44c5-9a10-7dfbb5f29112

PR:

https://github.com/ForNeVeR/bloodmasters/assets/38229504/3a8f8c5a-7b06-4d50-994c-d2f3bee9f265

Notice how bullets missing laser end dot

2023-10-12 08:21 UTC, y0ung3r commented
@KeterSCP If you pay attention to the angle at which the projectile flies out, it is clear that this problem is also present in the `main` branch. I didn't notice it last night when testing. But you are right, it shouldn't be

2023-10-12 09:52 UTC, y0ung3r commented
@KeterSCP I'll try to fix it when I have some free time. Thank you!

2023-10-14 13:53 UTC, ForNeVeR commented
> Seems like this pr also changes bullet's trajectories

JFYI, it is somewhat expected: see the discussion of #34 for more details.

2023-10-14 16:31 UTC, KeterSCP commented
Yeah, I know. But as you may notice on the second attachment video, bullets are now missing laser sight dot when facing west, which is also incorrect. It would be perfect to align bullet trajectory with laser sight

2023-10-15 11:53 UTC, ForNeVeR commented
> Yeah, I know. But as you may notice on the second attachment video, bullets are now missing laser sight dot when facing east, which is also incorrect. It would be perfect to align bullet trajectory with laser sight

Yep, on this I agree.

2023-10-15 12:04 UTC, ForNeVeR requested changes
I am okay with the proposed solution, but let's consider using this `GetProjectileInitialPosition` when drawing the laser sight as well? If I understand correctly, then we'll have 100% correct laser sight, and all the projectiles will launch from the weapon origin and not the player head.

2023-10-15 12:04 UTC, ForNeVeR commented on Source/Server/Weapons/WGrenadeLauncher.cs
> +        new Grenade(GetProjectileInitialPosition(client), vel, client);
If we don't want to use `PROJECTILE_Z` anymore, let's delete that variable from all the affected weapons (and I assume from _all_ the weapons, that is?).

2023-10-15 12:04 UTC, ForNeVeR commented on Source/Server/Weapons/WPhoenix.cs
> -        Vector3D pos = client.State.pos + Vector3D.FromActorAngle(client.AimAngle, client.AimAngleZ, PROJECTILE_OFFSET);
Please note that `PROJECTILE_OFFSET` was different from `WPhoenix` (I mean it is equal to `4f` for everyone _except_ Phoenix) before this change.

Perhaps we should parametrize the `GetProjectileInitialPosition` method instead?

2023-10-15 12:17 UTC, ForNeVeR requested changes
See the comments.

2023-11-23 19:07 UTC, y0ung3r commented
@ForNeVeR It still seems to me that there are a lot of potential problems in the proposed solution that are quite difficult to identify and verify. I think it is necessary to approach this problem from another side, but not in this PR anymore

2023-11-23 19:07 UTC, closed without merging